
name: iOS CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install xcpretty
      run: gem install xcpretty

    # - name: Set up Xcode
    #   run: sudo xcode-select -s /Applications/Xcode_12.5.app

    - name: Run build
      run: |
        xcodebuild \
          -scheme com.awareframework.ios.core \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0' \
          build | xcpretty

    - name: Run tests
      run: |
        xcodebuild \
          -scheme com.awareframework.ios.core \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0' \
          -sdk iphonesimulator \
          -configuration Debug \
          clean test | xcpretty